Update pre-commit hook to use spotless for kotlin
Signed-off-by: Álvaro Brey <alvaro.brey@nextcloud.com>

diff --git a/scripts/hooks/pre-commit b/scripts/hooks/pre-commit
--- a/scripts/hooks/pre-commit
+++ b/scripts/hooks/pre-commit
@@ -2,9 +2,9 @@
 # Pre-commit hook: don't allow commits if detekt or ktlint fail. Skip with "git commit --no-verify".
 echo "Running pre-commit checks..."
 
-if ! ./gradlew --daemon ktlintCheck &>/dev/null; then
-    echo >&2 "ktlint failed! Run ./gradlew ktlintCheck for details"
-    echo >&2 "Hint: fix most lint errors with ./gradlew ktlintFormat"
+if ! ./gradlew --daemon spotlessKotlinCheck &>/dev/null; then
+    echo >&2 "ktlint failed! Run ./gradlew spotlessKotlinCheck for details"
+    echo >&2 "Hint: fix most lint errors with ./gradlew spotlessKotlinApply"
     exit 1
 fi
 
